In [3]:
distance = [10, 15, 17, 26]
time = [.30, .47, .55, 1.20]

speed = distance/time

TypeError: unsupported operand type(s) for /: 'list' and 'list'

__Though you can change individual values in a list, you can not apply a mathematical operation over the entire list.__ Here comes Numpy for rescue.

- Numpy is a Python library, that supports a data container called Arrays. __Arrays are like Lists but they can do something that Lists can't. They easily allow you to perform mathematical operations over the entire dataset.__  

In [4]:
import numpy as np

#converting lists into numpy arrays
np_distance = np.array(distance)
np_time = np.array(time)

speed = np_distance/np_time
speed

array([33.33333333, 31.91489362, 30.90909091, 21.66666667])

- __NumPy (Numerical Python) is the foundational package for mathematical computing in Python.__
- It supports fast and efficient multidimensional arrays (ndarray).
- Executes element-wise computations and mathematical calculations.
- Performs linear algebraic operations, Fourier transforms and random number generation.
- It has tools for reading/writing array based datasets to disk.
- It has efficient way of storing and manipulating data.
- __An array is a collection of values that can be added, removed and changed just like a list but unlike a list it is homogeneous i.e. it can only hold a single type of data. It is multidimensional (Arrays can be one dimensional, two dimensional or multi-dimensional) & supports mathematical functions. It is Fast and efficient.__
- An array is basically nothing but pointers. It’s a combination of a memory address, a data type, a shape, and strides:  
__(1)__ The __data__ pointer indicates the memory address of the first byte in the array.  
__(2)__ The data type or __dtype__ pointer describes the kind of elements that are contained within the array.  
__(3)__ The __shape__ indicates the shape of the array.  
__(4)__ The __strides__ are the number of bytes that should be skipped in memory to go to the next element. If your strides are (10,1), you need to proceed one byte to get to the next column and 10 bytes to locate the next row.

In [2]:
#import Numpy library
import numpy as np

#first numpy array
first_numpy_array = np.array([1, 2, 3, 4])
print(first_numpy_array)

[1 2 3 4]


In [3]:
#printing out memory address
print(first_numpy_array.data)

In [4]:
#printing out shape of array
print(first_numpy_array.shape)

(4,)


In [5]:
#printing out the data type of array
print(first_numpy_array.dtype)  #each integer takes up 4 bytes and we have an array of 4 integers (4 * 4 = 16 bytes)
#in case of 'int64' each integer takes up 8 bytes.

int32


In [6]:
#printing out the stride of array
print(first_numpy_array.strides)

(4,)


In [7]:
import numpy as np

arr1 = np.array([10, 12, 13, 15, 17])
arr1.flags     #Information about the memory layout of the array.

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

- __Ask For Help:__

In [36]:
import numpy as np

print(np.lookfor("zeros"))

Search results for 'zeros'
--------------------------
numpy.zeros
    Return a new array of given shape and type, filled with zeros.
numpy.eye
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
numpy.tri
    An array with ones at and below the given diagonal and zeros elsewhere.
numpy.trim_zeros
    Trim the leading and/or trailing zeros from a 1-D array or sequence.
numpy.zeros_like
    Return an array of zeros with the same shape and type as a given array.
numpy.ma.zeros
    Return a new array of given shape and type, filled with zeros.
numpy.nancumsum
    Return the cumulative sum of array elements over a given axis treating Not a
numpy.matlib.zeros
    Return a matrix of given shape and type, filled with zeros.
numpy.char.zfill
    Return the numeric string left-filled with zeros
numpy.bytes0.zfill
    Pad a numeric string with zeros on the left, to fill a field of the given width.
numpy.matlib.eye
    Return a matrix with ones on the diagonal and zeros elsewhere

In [40]:
import numpy as np

np.info("zeros")

     *** Found in numpy ***
zeros(shape, dtype=float, order='C')

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Also
--------
zeros_like : Return an array of zeros with shape and type of input.
empty : Return a new uninitialized array.
ones : Return a new array setting values to one.
full : Return a new array of given shape filled with value.

Examples
--------
>>> np.zeros(5)
array([ 0.,  0.,  0.,  0.,  0.])

>>> np.zeros((5,), dtype=int)
array([0, 0, 0, 0, 0])

>>> np.zeros((2, 1))
arr

### Purpose of ndarray:  
- Data Scientists write a program to solve a problem. A program can have multiple algorithms that contain business logics such as functions or element-wise computations or mathematical operations. Algorithms within a program need to share data to manipulate it and execute the embedded logic and __ndarray__ makes this task simple. __The ndarray in Python is used as the primary container to exchange data between algorithms for fast and efficient computing.__

In [171]:
#array with zeros
array_with_zeros = np.zeros((3,3))
array_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [176]:
array_with_zeros = np.zeros((2,3,4))    #it defines 2 arrays & each of 3 rows and 4 columns
array_with_zeros

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [172]:
#array with ones
array_with_ones = np.ones((3,3))
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [173]:
#array with empty
array_with_empty = np.empty((2,3))  #array will contain random numbers unless you set them manually
array_with_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [177]:
#array with random values
np.random.random((2,2))

array([[0.65252671, 0.32647725],
       [0.6588142 , 0.89386881]])

In [178]:
#full array
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [7]:
#array with arange() method
#arange() method is used to create numpy arrays of certain data length
np_arange = np.arange(12)     #one-dimensional array will be returned
print(np_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [183]:
#arange() method helps to create an array of evenly-spaced values
np.arange(10, 25, 5)

array([10, 15, 20])

In [14]:
#linspace() for linearly(equal) spaced data elements array creation
#1st argument indicates the start element of the array.
#2nd argument indicates the end element of the array.
#3rd argument indicates the total number of equidistant elements including the 1st & last element
np_linspace = np.linspace(1, 6, 5)
print(np_linspace)

[1.   2.25 3.5  4.75 6.  ]


In [11]:
#reshape() method to change the array
#changing above one dimensional array to two dimensional array
np_arange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
import numpy as np

arr = np.array([1.5, 1.6, 1, 3, 6.4])
print(arr)

[1.5 1.6 1.  3.  6.4]


In [15]:
#changing the data type of an array but it will not change the actual data in arr
arr.astype(int)

array([1, 1, 1, 3, 6])

In [16]:
print(arr)

[1.5 1.6 1.  3.  6.4]


### One dimensional array
- arange() & reshape() can be used to create one dimensional array.

In [16]:
oneD_array = np.arange(15)
oneD_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Two dimensional array
- arange() & reshape() can be used to create two dimensional array.

In [18]:
twoD_array = oneD_array.reshape(3,5)    #3 rows and 5 columns
print(twoD_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


### Three Dimensional array
- arange() & reshape() can be used to create three dimensional array.

In [19]:
ThreeD_array = np.arange(27).reshape(3, 3, 3)
print(ThreeD_array)    #3 dimensional square array

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


- In a 2D array, rows are indicated as the “axis 0”, while the columns are the “axis 1”. The number of the axis goes up accordingly with the number of the dimensions: in 3-D arrays, you’ll have an additional “axis 2”.
- These axes are only valid for arrays that have at least 2 dimensions, as there is no point in having this for 1-D arrays. These axes will come in handy later when you’re manipulating the shape of your NumPy arrays.

__Identity Array or Matrix__
- An identity matrix is a square matrix of which all elements in the principal diagonal are ones, and all other elements are zeros.
- When you multiply a matrix with an identity matrix, the resulting product will be the same matrix.

In [186]:
#eye() to create identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [187]:
#identity() to create identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Class and Attributes of ndarray
- NumPy's array class is "ndarray", also referred as "__numpy.ndarray__". ndarray stands for n dimensional array.
- Attributes define the properties of an object. The attributes of ndarray are:  
__(1) ndarray.ndim :__ This refers to the number of axes (dimensions) of the array. It is also called as the rank of the array.

In [20]:
np_city = np.array(["NYC", "LA", "Miami", "Houston"])
np_city.ndim

1

In [21]:
np_city_with_state = np.array([["NYC", "LA", "Miami", "Houston"],["NY", "CA", "FL", "TX"]])
np_city_with_state.ndim

2

In [22]:
np_city_with_state

array([['NYC', 'LA', 'Miami', 'Houston'],
       ['NY', 'CA', 'FL', 'TX']], dtype='<U7')

  
__(2) ndarray.shape :__ This describes the structure of an array. This consists of a tuple of integers showing the size of the array in each dimension. __The length of the 'shape tuple' is the rank or ndim.__

In [17]:
np_city = np.array(["NYC", "LA", "Miami", "Houston"])
np_city_with_state = np.array([["NYC", "LA", "Miami", "Houston"],["NY", "CA", "FL", "TX"]])

In [18]:
np_city.shape    #4 columns.

(4,)

In [20]:
len(np_city.shape)    #Rank of array = 1

1

In [21]:
np_city_with_state.shape    #2 rows and 4 columns.

(2, 4)

In [23]:
len(np_city_with_state.shape)     #Rank of array = 2

2

__(3) ndarray.size :__ This gives the total number of elements in the array. It is equal to the product of the elements of the shape tuple.

In [28]:
np_city.size

4

In [29]:
np_city_with_state.size

8

__(4) ndarray.dtype :__ This describes the type of the elements in the array.

In [34]:
np_city

array(['NYC', 'LA', 'Miami', 'Houston'], dtype='<U7')

In [36]:
np_city.dtype

dtype('<U7')

In [37]:
np_city_with_state

array([['NYC', 'LA', 'Miami', 'Houston'],
       ['NY', 'CA', 'FL', 'TX']], dtype='<U7')

In [38]:
np_city_with_state.dtype

dtype('<U7')

In [25]:
a1 = np.arange(8)
a1

array([0, 1, 2, 3, 4, 5, 6, 7])

In [26]:
a1.dtype

dtype('int32')

### How To Load NumPy Arrays From Text
- Creating arrays with the help of initial placeholders or with some example data is an excellent way of getting started with numpy. But when you want to get started with data analysis, you’ll need to load data from text files.
- Make use of some specific functions to load data from your files, such as __loadtxt()__ or __genfromtxt()__.
- First argument that both functions take is the text file.
- __loadtxt() arguments:__  
__(1)skiprows__ argument is to skip specific row.  
__(2)unpack__ argument return the columns as separate arrays with __unpack=TRUE__. In the below example values in column Value1 will be put in x, and so on.  
__(3)delimiter__ argument is to add a delimeter like comma(,) in case you have comma-delimited data.  
__(4)dtype__ argument is to specify the data type.  
- __genfromtxt() arguments:__  
__(1)skip_header__ argument is to set number of lines to skip at the beginning of the file.  
__(2)skip_footer__ argument is to set number of lines to skip at the end of the file.  
__(3)missing_values__ argument is to set strings corresponding to missing data.  
__(4)filling_values__ argument is to set values as default when the data are missing.

### loading numpy array using loadtxt():

In [2]:
#exampl1
import numpy as np

x1, y1, z1 = np.loadtxt('D:\\PGP_DataScience_Purdue_Simplilearn\\Python Practice\\Countries with GDP2.txt', 
                        skiprows=1, unpack = True)

In [3]:
x1

array([0.2536, 0.4839, 0.1292, 0.1781, 0.6253])

In [4]:
y1

array([0.1008, 0.4536, 0.6875, 0.3049, 0.3486])

In [5]:
z1

array([0.3857, 0.3561, 0.5929, 0.8928, 0.8791])

In [6]:
x,y,z = np.loadtxt('C:\\Users\\HP\\Desktop\\New folder\\Python\\data.txt', skiprows=1, unpack = True)

In [7]:
x

array([0.2536, 0.4839, 0.1292, 0.1781, 0.6253])

In [8]:
y

array([0.1008, 0.4536, 0.6875, 0.3049, 0.3486])

In [9]:
z

array([0.3857, 0.3561, 0.5929, 0.8928, 0.8791])

In [10]:
x + y

array([0.3544, 0.9375, 0.8167, 0.483 , 0.9739])

In [11]:
x - y

array([ 0.1528,  0.0303, -0.5583, -0.1268,  0.2767])

In [12]:
x * y

array([0.02556288, 0.21949704, 0.088825  , 0.05430269, 0.21797958])

In [13]:
x2 = list(x)   #converting array to list
print(x1)
y2 = list(y)
print(y1)

z2 = np.array([x1, y1], dtype = np.float16)  #creating new array using the above converted arrays to list
print(z2)

[0.2536 0.4839 0.1292 0.1781 0.6253]
[0.1008 0.4536 0.6875 0.3049 0.3486]
[[0.2537 0.484  0.1292 0.1781 0.6255]
 [0.1008 0.4536 0.6875 0.305  0.3486]]


### loading numpy array using genfromtxt():
- __genfromtxt()__ gives you a little bit more flexibility; It’s more robust than loadtxt().
- __loadtxt() only works when each row in the text file has the same number of values; So when you want to handle missing values easily, you’ll typically find it easier to use genfromtxt().__

In [46]:
my_array = np.genfromtxt('D:\\PGP_DataScience_Purdue_Simplilearn\\Python Practice\\Countries with GDP2.txt',
                     skip_header = 1)
my_array

array([[0.2536, 0.1008, 0.3857],
       [0.4839, 0.4536, 0.3561],
       [0.1292, 0.6875, 0.5929],
       [0.1781, 0.3049, 0.8928],
       [0.6253, 0.3486, 0.8791]])

In [47]:
my_array[0]

array([0.2536, 0.1008, 0.3857])

In [48]:
my_array[0:3,]

array([[0.2536, 0.1008, 0.3857],
       [0.4839, 0.4536, 0.3561],
       [0.1292, 0.6875, 0.5929]])

In [13]:
#exampl2 with missing values
my_array2 = np.genfromtxt("C:\\Users\\HP\\Desktop\\New folder\\Python\\data2.txt",
                         skip_header = 1, filling_values = -999)
my_array2

array([[ 4.839e-01,  4.536e-01,  3.561e-01],
       [ 1.292e-01,  6.875e-01, -9.990e+02],
       [ 1.781e-01,  3.049e-01,  8.928e-01],
       [-9.990e+02,  5.801e-01,  2.038e-01],
       [ 5.993e-01,  4.357e-01,  7.410e-01]])

-  __genfromtxt__ runs two main loops. The first loop converts each line of the file in a sequence of strings. The second loop converts each string to the appropriate data type. This mechanism is slower than a single loop, but gives more flexibility. In particular, genfromtxt is able to take missing data into account, when other faster and simpler functions like loadtxt cannot.
- The only mandatory argument of genfromtxt is the source of the data. It can be a string, a list of strings, a generator or an open file-like object with a read method, for example, a file or __io.StringIO__ object. If a single string is provided, it is assumed to be the name of a local or remote file. If a list of strings or a generator returning strings is provided, each string is treated as one line in a file. When the URL of a remote file is passed, the file is automatically downloaded to the current directory and opened.
- Recognized file types are text files and archives. Currently, the function recognizes gzip and bz2 (bzip2) archives. The type of the archive is determined from the extension of the file: if the filename ends with '.gz', a gzip archive is expected; if it ends with 'bz2', a bzip2 archive is assumed.
- Once the file is defined and open for reading, __delimiter__ keyword of genfromtxt splits each non-empty line into a sequence of strings. Empty or commented lines are just skipped. The delimiter keyword is used to define how the splitting should take place. Quite often, a single character marks the separation between columns. For example, comma-separated files (CSV) use a comma (,) or a semicolon (;) as delimiter.

- The presence of a header in the file can hinder data processing. In that case, we need to use the __skip_header__ optional argument. The values of this argument must be an integer which corresponds to the number of lines to skip at the beginning of the file, before any other action is performed. Similarly, we can skip the last n lines of the file by using the __skip_footer__ attribute and giving it a value of n.

In [39]:
data = u"\n".join(str(i) for i in range(10))

np.genfromtxt(StringIO(data),)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [40]:
np.genfromtxt(StringIO(data),skip_header=3, skip_footer=5)

array([3., 4.])

In [43]:
my_array2 = np.genfromtxt("C:\\Users\\HP\\Desktop\\New folder\\Python\\data4.txt",
                         skip_header = 1, skip_footer = 4, filling_values = -999)
my_array2

array([[ 4.839e-01,  4.536e-01,  3.561e-01],
       [ 1.292e-01,  6.875e-01, -9.990e+02],
       [ 1.781e-01,  3.049e-01,  8.928e-01]])

In [44]:
my_array2 = np.genfromtxt("C:\\Users\\HP\\Desktop\\New folder\\Python\\data4.txt",
                         skip_header = 1, skip_footer = 2, filling_values = -999)
my_array2

array([[ 4.839e-01,  4.536e-01,  3.561e-01],
       [ 1.292e-01,  6.875e-01, -9.990e+02],
       [ 1.781e-01,  3.049e-01,  8.928e-01],
       [-9.990e+02,  5.801e-01,  2.038e-01],
       [ 5.993e-01,  4.357e-01,  7.410e-01]])

- Since the __genfromtxt() function converts character strings in numeric columns to nan__, you can convert these values to other ones by specifying the __filling_values__ argument. In the above case, we choose to set the value of these missing values to -999.

In [14]:
my_array3 = np.genfromtxt("C:\\Users\\HP\\Desktop\\New folder\\Python\\data2.txt", skip_header = 1)
my_array3

array([[0.4839, 0.4536, 0.3561],
       [0.1292, 0.6875,    nan],
       [0.1781, 0.3049, 0.8928],
       [   nan, 0.5801, 0.2038],
       [0.5993, 0.4357, 0.741 ]])

- If by any chance, you have values that don’t get converted to nan by genfromtxt(), there’s always the __missing_values__ argument that allows you to specify what the missing values of your data exactly are.
- Using __max_rows__ argument we can specify the maximum number of rows, we can read.

In [17]:
my_array3 = np.genfromtxt("C:\\Users\\HP\\Desktop\\New folder\\Python\\data2.txt", skip_header = 1, max_rows = 3)
my_array3

array([[0.4839, 0.4536, 0.3561],
       [0.1292, 0.6875,    nan],
       [0.1781, 0.3049, 0.8928]])

In [24]:
#reading csv file
my_array4 = np.genfromtxt("C:\\Users\\HP\\Desktop\\New folder\\Python\\data3.csv", skip_header = 2, delimiter = ',')
my_array4

array([[0.4839, 0.4536, 0.3561],
       [0.1292, 0.6875,    nan],
       [0.1781, 0.3049, 0.8928],
       [   nan, 0.5801, 0.2038],
       [0.5993, 0.4357, 0.741 ]])

In [29]:
#In the data3.csv 1st two rows are normal text. So if we use skip_header = 1, it will give nan for one text row
my_array5 = np.genfromtxt("C:\\Users\\HP\\Desktop\\New folder\\Python\\data3.csv", 
                          skip_header = 1, delimiter = ',', filling_values = -99)
print("my_array5 is: \n", my_array5)

#if we use skip_header = 0, it will give error
my_array6 = np.genfromtxt("C:\\Users\\HP\\Desktop\\New folder\\Python\\data3.csv", skip_header = 0, delimiter = ',')
print("my_array5 is: ", my_array6)

my_array5 is: 
 [[-99.     -99.     -99.    ]
 [  0.4839   0.4536   0.3561]
 [  0.1292   0.6875 -99.    ]
 [  0.1781   0.3049   0.8928]
 [-99.       0.5801   0.2038]
 [  0.5993   0.4357   0.741 ]]


ValueError: Some errors were detected !
    Line #2 (got 3 columns instead of 1)
    Line #3 (got 3 columns instead of 1)
    Line #4 (got 3 columns instead of 1)
    Line #5 (got 3 columns instead of 1)
    Line #6 (got 3 columns instead of 1)
    Line #7 (got 3 columns instead of 1)

In [30]:
import numpy as np
from io import StringIO

data = u"1, 2, 3\n4, 5, 6"
np.genfromtxt(StringIO(data), delimiter= ",")

array([[1., 2., 3.],
       [4., 5., 6.]])

- By default, genfromtxt assumes delimiter=None, meaning that the line is split along white spaces (including tabs) and that consecutive white spaces are considered as a single white space.
- We may be dealing with a fixed-width file, where columns are defined as a given number of characters. In that case, we need to set delimiter to a single integer (if all the columns have the same size) or to a sequence of integers (if columns can have different sizes).

In [32]:
import numpy as np
from io import StringIO

data = u"  1  2  3\n  4  5 67\n890123  4"
np.genfromtxt(StringIO(data), delimiter=3)

array([[  1.,   2.,   3.],
       [  4.,   5.,  67.],
       [890., 123.,   4.]])

In [33]:
import numpy as np
from io import StringIO

data = u"123456789\n   4  7 9\n   4567 9"
np.genfromtxt(StringIO(data), delimiter= (4, 3, 2))

array([[1234.,  567.,   89.],
       [   4.,    7.,    9.],
       [   4.,  567.,    9.]])

- By default, when a line is decomposed into a series of strings, the individual entries are not stripped of leading nor trailing white spaces. This behavior can be overwritten by setting the optional argument __autostrip__ to a value of True.

In [35]:
import numpy as np
from io import StringIO

data = u"1, abc , 2\n 3, xxx, 4"
#without autostrip
np.genfromtxt(StringIO(data), delimiter = ",", dtype = "|U5")

array([['1', ' abc ', ' 2'],
       ['3', ' xxx', ' 4']], dtype='<U5')

In [36]:
#with autostrip
np.genfromtxt(StringIO(data), delimiter = ",", dtype = "|U5", autostrip = True)

array([['1', 'abc', '2'],
       ['3', 'xxx', '4']], dtype='<U5')

- The optional argument __comments__ is used to define a character string that marks the beginning of a comment. By default, genfromtxt assumes comments='#'. The comment marker may occur anywhere on the line. Any character present after the comment marker(s) is simply ignored.

In [37]:
data = u"""#
# Skip me !
# Skip me too !
1, 2
3, 4
5, 6 #This is the third line of the data
7, 8
# And here comes the last line
9, 0
"""

np.genfromtxt(StringIO(data), comments = "#", delimiter = ",")

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.],
       [9., 0.]])

- In some cases, we are not interested in all the columns of the data but only a few of them. We can select which columns to import with the __usecols__ argument. This argument accepts a single integer or a sequence of integers corresponding to the indices of the columns to import. Remember that by convention, the first column has an index of 0. Negative integers behave the same as regular Python negative indexes.

In [1]:
import numpy as np
from io import StringIO

data = u"1 2 3\n4 5 6"
np.genfromtxt(StringIO(data), usecols = (0, -1))

array([[1., 3.],
       [4., 6.]])

- If the columns have names, we can also select which columns to import by giving their name to the usecols argument, either as a sequence of strings or a comma-separated string.

In [2]:
data = u"1 2 3\n4 5 6"
np.genfromtxt(StringIO(data), names = "a, b, c", usecols=("a", "c"))

array([(1., 3.), (4., 6.)], dtype=[('a', '<f8'), ('c', '<f8')])

In [3]:
np.genfromtxt(StringIO(data), names = "a, b, c", usecols = ("a, c"))

array([(1., 3.), (4., 6.)], dtype=[('a', '<f8'), ('c', '<f8')])

- The main way to control how the sequences of strings we have read from the file are converted to other types is to set the __dtype__ argument. Acceptable values for this argument are:  
(1) a single type, such as dtype=float. The output will be 2D with the given dtype, unless a name has been associated with each column with the use of the __names__ argument. dtype=float is the default for genfromtxt.  
(2) a sequence of types, such as dtype=(int, float, float).  
(3) a comma-separated string, such as dtype="i4,f8,|U3".  
(4) a dictionary with two keys 'names' and 'formats'.  
(5) a sequence of tuples (name, type), such as dtype=[('A', int), ('B', float)].  
(6) an existing numpy.dtype object.  
(7) the special value None. In that case, the type of the columns will be determined from the data itself.  
In all the cases but the first one, the output will be a 1D array with a structured dtype. This dtype has as many fields as items in the sequence.

- We may sometimes need to define the column names from the data itself. In that case, we must use the __names__ keyword with a value of True. The names will then be read from the first line (after the skip_header ones), even if the line is commented out.

In [4]:
import numpy as np
from io import StringIO

data = StringIO("So it goes\n#a b c\n1 2 3\n 4 5 6")
np.genfromtxt(data, skip_header = 1, names = True)

array([(1., 2., 3.), (4., 5., 6.)],
      dtype=[('a', '<f8'), ('b', '<f8'), ('c', '<f8')])

In [6]:
import numpy as np

new_data = np.genfromtxt("C:\\Users\\HP\\Desktop\\New folder\\Python\\data5.txt", skip_header = 1, 
                         names = True, filling_values = -99)
new_data

array([(  0.4839, 0.4536,   0.3561), (  0.1292, 0.6875, -99.    ),
       (  0.1781, 0.3049,   0.8928), (-99.    , 0.5801,   0.2038),
       (  0.5993, 0.4357,   0.741 )],
      dtype=[('Value1', '<f8'), ('Value2', '<f8'), ('Value3', '<f8')])

In [7]:
import numpy as np
from io import StringIO

data = StringIO("1 2 3\n 4 5 6")
ndtype=[('a',int), ('b', float), ('c', int)]
names = ["A", "B", "C"]

np.genfromtxt(data, names = names, dtype = ndtype)

array([(1, 2., 3), (4, 5., 6)],
      dtype=[('A', '<i4'), ('B', '<f8'), ('C', '<i4')])

### How to save NumPy Arrays
- Once you have done everything that you need to do with your arrays, you can also save them to a file. If you want to save the array to a text file, you can use the __savetxt()__ function to do this.
- __save()__ Saves an array to a binary file in NumPy .npy format.
- __savez()__ Saves several arrays into an uncompressed .npz archive.
- __savez_compressed()__ Saves several arrays into a compressed .npz archive.

In [34]:
import numpy as np
x = np.arange(0, 14, 3)
np.savetxt('D:\\PGP_DataScience_Purdue_Simplilearn\\Python Practice\\test.txt', x, delimiter = ',')

In [8]:
import numpy as np
from io import StringIO

data = StringIO("1 2 3\n 4 5 6")
ndtype=[('a',int), ('b', float), ('c', int)]
names = ["A", "B", "C"]

array_data = np.genfromtxt(data, names = names, dtype = ndtype)
np.savetxt("C:\\Users\\HP\\Desktop\\New folder\\Python\\test01.txt", array_data, delimiter = ',')

### Basic Operations
__(1) Mathematical Operations__:  
- Broadcasting is a mechanism that allows NumPy to work with arrays of different shapes when you’re performing arithmetic operations. To put it in a more practical context, you often have an array that’s somewhat larger and another one that’s slightly smaller. Ideally, you want to use the smaller array multiple times to perform an operation (such as a sum, multiplication, etc.) on the larger array. To do this, you use the broadcasting mechanism.  
- To make sure that the broadcasting is successful, the dimensions of your arrays need to be compatible. Two dimensions are compatible when they are equal.
- Two dimensions are also compatible when one of them is 1.
- The arrays can only be broadcast together if they are compatible in all dimensions.  
If the dimensions are not compatible, you will get a __ValueError__. 
- Test what the size of the resulting array is after you have done the computations! You’ll see that the size is actually the maximum size along each dimension of the input arrays.
- In case dimensions are not compatible, you’ll have to fix this by manipulating your array.

In [19]:
import numpy as np

#initialize 'x'
x = np.ones((3,4))
print(x)

#shape of 'x'
print(x.shape)

#initialize 'y'
y = np.arange(4)
print(y)

#shape of 'y'
print(y.shape)

#subtract 'x' and 'y'
print(x - y)
print((x - y).shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(3, 4)
[0 1 2 3]
(4,)
[[ 1.  0. -1. -2.]
 [ 1.  0. -1. -2.]
 [ 1.  0. -1. -2.]]
(3, 4)


In [21]:
import numpy as np

#initialize 'x' and 'y'
x = np.ones((3,4))
y = np.random.random((5,1,4))
print(y)

#add 'x' and 'y'
print(x + y)

[[[0.13751408 0.08005897 0.06534499 0.27126135]]

 [[0.8967328  0.39443274 0.60838385 0.12698334]]

 [[0.60399621 0.43351102 0.62992971 0.29461246]]

 [[0.65773273 0.68179338 0.10598663 0.73390807]]

 [[0.06469299 0.48933337 0.05843324 0.62191003]]]
[[[1.13751408 1.08005897 1.06534499 1.27126135]
  [1.13751408 1.08005897 1.06534499 1.27126135]
  [1.13751408 1.08005897 1.06534499 1.27126135]]

 [[1.8967328  1.39443274 1.60838385 1.12698334]
  [1.8967328  1.39443274 1.60838385 1.12698334]
  [1.8967328  1.39443274 1.60838385 1.12698334]]

 [[1.60399621 1.43351102 1.62992971 1.29461246]
  [1.60399621 1.43351102 1.62992971 1.29461246]
  [1.60399621 1.43351102 1.62992971 1.29461246]]

 [[1.65773273 1.68179338 1.10598663 1.73390807]
  [1.65773273 1.68179338 1.10598663 1.73390807]
  [1.65773273 1.68179338 1.10598663 1.73390807]]

 [[1.06469299 1.48933337 1.05843324 1.62191003]
  [1.06469299 1.48933337 1.05843324 1.62191003]
  [1.06469299 1.48933337 1.05843324 1.62191003]]]


In [40]:
first_trial_cyclist = [10, 15, 17, 26]
second_trial_cyclist = [12, 11, 21, 24]
np_first_trial_cyclist = np.array(first_trial_cyclist)
np_second_trial_cyclist = np.array(second_trial_cyclist)

#vector addition (addition takes place element by element i.e. element wise operation)
np_first_trial_cyclist + np_second_trial_cyclist

array([22, 26, 38, 50])

In [41]:
#addition by add()
import numpy as np

np.add(45, 20)

65

In [42]:
#subtraction by subtract()
np.subtract(45, 23)

22

In [43]:
#multiplication
#number of hrs worked for 5 days
#hourly rate is 15 USD
np_daily_wage = np.array([7, 9, 13, 8, 11]) * 15
np_daily_wage

array([105, 135, 195, 120, 165])

In [55]:
#multiplication by multiply()
np.multiply(2,5)

10

In [56]:
#division by divide()
np.divide(2,10)

0.2

In [57]:
np.divide(10,2)

5.0

In [58]:
#remainder by remainder()
np.remainder(11,2)

1

In [44]:
#sum() to add all data elements of ndarray
#total earning after 5 days
sum(np_daily_wage)

720

__(2) Comparison Operations__

In [2]:
import numpy as np

#ndarray for weekly hrs, 5 consecutive weeks hrs data
np_weekly_hrs = np.array([23, 41, 55, 47, 38])
#week with more than 40hrs
np_weekly_hrs[np_weekly_hrs > 40]

array([41, 55, 47])

In [3]:
np_weekly_hrs > 40

array([False,  True,  True,  True, False])

In [4]:
#week with not equal to 40 hrs
np_weekly_hrs[np_weekly_hrs != 40]

array([23, 41, 55, 47, 38])

__Comparing entire arrays with each other__:

In [71]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1, 2, 3, 4, 5])

np.array_equal(arr1, arr2)

True

In [72]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 4, 6, 8, 10])

np.array_equal(arr1, arr2)

False

__(3) Logical Operations__

In [5]:
#logical AND operation
np.logical_and(np_weekly_hrs>20, np_weekly_hrs<50)

array([ True,  True, False,  True,  True])

In [7]:
#logical OR operation
np.logical_or(np_weekly_hrs>20, np_weekly_hrs<50)

array([ True,  True,  True,  True,  True])

In [6]:
#logical NOT operation
np.logical_not(np_weekly_hrs>35)

array([ True, False, False, False, False])

## Accessing Array Elements
__(1) Indexing__

In [23]:
cyclist_trials = np.array([[10,15,17,26],[12,11,21,24]])
cyclist_trials

array([[10, 15, 17, 26],
       [12, 11, 21, 24]])

In [24]:
first_trial = cyclist_trials[0]
first_trial

array([10, 15, 17, 26])

In [25]:
second_trial = cyclist_trials[1]
second_trial

array([12, 11, 21, 24])

In [26]:
first_cyclist_first_trial = cyclist_trials[0][0]
first_cyclist_first_trial

10

In [27]:
first_cyclist_second_trial = cyclist_trials[1][0]
first_cyclist_second_trial

12

In [28]:
first_cyclist_second_trial = cyclist_trials[1,0]
first_cyclist_second_trial

12

In [17]:
first_cyclist_all_trials = cyclist_trials[:,0]
first_cyclist_all_trials

array([10, 12])

In [22]:
import numpy as np

arr1 = np.array([[[1, 2, 3, 4],[5, 6, 7, 8]], [[10, 11, 12, 13],[14, 15, 16, 17]]])
print(arr1)
print(arr1[1,1,2])

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[10 11 12 13]
  [14 15 16 17]]]
16


__(2) Slicing__
- Slicing is a data wrangling technique to access a particular range of data for a given dataset.

In [18]:
cyclist_trials.shape

(2, 4)

In [19]:
two_cyclist_trial_data = cyclist_trials[:,1:3]
two_cyclist_trial_data

array([[15, 17],
       [11, 21]])

__(3) Iteration__

In [20]:
for iterate_cyclist_trials_data in cyclist_trials:
    print(iterate_cyclist_trials_data)

[10 15 17 26]
[12 11 21 24]


In [21]:
for iterate_two_cyclist_trial_data in two_cyclist_trial_data:
    print(iterate_two_cyclist_trial_data)

[15 17]
[11 21]


### Indexing with Boolean Arrays
- Boolean arrays are useful when you need to sort a dataset according to a set criteria. Instead of selecting elements, rows or columns based on index number, you select those values from your array that fulfill a certain condition.

In [30]:
test_scores = np.array([[83,71,57,63],[54,68,81,45]])
test_scores

array([[83, 71, 57, 63],
       [54, 68, 81, 45]])

In [31]:
passing_score = test_scores > 60
passing_score

array([[ True,  True, False,  True],
       [False,  True,  True, False]])

In [32]:
#selecting those values from the test_scores array that fulfill the condition of test_scores > 60
test_scores[passing_score]

array([83, 71, 63, 68, 81])

- Fancy way to perform indexing around the array

In [35]:
import numpy as np

arr1 = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])  #2d array
print(arr1)

print(arr1[[1, 0, 1, 0],[0, 1, 2, 0]])   
#here [1, 0, 1, 0] defines the rows and [0, 1, 2, 0] defines the columns. We have to see by keeping them together.
#e.g. [1, 0], [0, 1], [1, 2], [0, 0]

[[1 2 3 4]
 [5 6 7 8]]
[5 2 7 1]


## Copy and Views
__(1) Simple Assignments__ : In this method, a variable is directly assigned the value of another variable. No new copy is made.

In [44]:
NYC_Borough = np.array(["Manhattan","Bronx","Brooklyn","Staten Island","Queens"])
NYC_Borough

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Queens'],
      dtype='<U13')

In [45]:
Boroughs_in_NYC = NYC_Borough
Boroughs_in_NYC

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Queens'],
      dtype='<U13')

In [46]:
Boroughs_in_NYC is NYC_Borough    #shows both objects are same

True

In [47]:
#Change in Boroughs_in_NYC will change the values in NYC_Borough, which we dont actually want always.
Boroughs_in_NYC[3] = "Michigan"
Boroughs_in_NYC

array(['Manhattan', 'Bronx', 'Brooklyn', 'Michigan', 'Queens'],
      dtype='<U13')

In [48]:
NYC_Borough

array(['Manhattan', 'Bronx', 'Brooklyn', 'Michigan', 'Queens'],
      dtype='<U13')

__(2) View/Shallow Copy__ : A view creates a new array object.

In [49]:
Boroughs_in_NYC

array(['Manhattan', 'Bronx', 'Brooklyn', 'Michigan', 'Queens'],
      dtype='<U13')

In [50]:
View_of_Boroughs_in_NYC = Boroughs_in_NYC.view()
View_of_Boroughs_in_NYC

array(['Manhattan', 'Bronx', 'Brooklyn', 'Michigan', 'Queens'],
      dtype='<U13')

In [51]:
len(View_of_Boroughs_in_NYC)

5

In [52]:
View_of_Boroughs_in_NYC is Boroughs_in_NYC    #View and Original object are different

False

In [53]:
#Change in View_of_Boroughs_in_NYC will change the values in Boroughs_in_NYC, which we dont actually want always.
View_of_Boroughs_in_NYC[4] = "Chicago"
View_of_Boroughs_in_NYC

array(['Manhattan', 'Bronx', 'Brooklyn', 'Michigan', 'Chicago'],
      dtype='<U13')

In [54]:
Boroughs_in_NYC    #Original dataset changed

array(['Manhattan', 'Bronx', 'Brooklyn', 'Michigan', 'Chicago'],
      dtype='<U13')

__(3) Copy/Deep Copy__ : It entirely copies the original dataset. Any change in the copy will not affect the original dataset.

In [55]:
Copy_of_NYC_Borough = NYC_Borough.copy()
Copy_of_NYC_Borough

array(['Manhattan', 'Bronx', 'Brooklyn', 'Michigan', 'Chicago'],
      dtype='<U13')

In [56]:
Copy_of_NYC_Borough is NYC_Borough    #Copy and original object are different

False

In [57]:
Copy_of_NYC_Borough.base is NYC_Borough    #Copy object data is not owned by the original dataset

False

In [58]:
#Change in Copy_of_NYC_Borough will not change the values in NYC_Borough
Copy_of_NYC_Borough[1] = "Ohaio"
Copy_of_NYC_Borough

array(['Manhattan', 'Ohaio', 'Brooklyn', 'Michigan', 'Chicago'],
      dtype='<U13')

In [60]:
NYC_Borough    #Original object data is not changed

array(['Manhattan', 'Bronx', 'Brooklyn', 'Michigan', 'Chicago'],
      dtype='<U13')

## Aggregate Functions:
__sum()__ : Array-wise sum. It will return sum of entier elements of the array.  
__min()__ : Array-wise minimum value  
__max(axis=0)__ : Maximum value of an array row  
__cumsum(axis=1)__ : Cumulative sum of the elements  
__mean()__ : Mean  
__median()__ : Median  
__corrcoef()__ : Correlation coefficient  
__std()__ : Standard deviation

In [11]:
arr1 = np.array([10, 12, 13, 15, 17])

In [12]:
#sum()
arr1.sum()

67

In [13]:
#min()
arr1.min()

10

In [14]:
#max()
arr1.max()

17

In [15]:
#cumsum()
arr2 = np.arange(12).reshape(3,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
arr2.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66], dtype=int32)

In [17]:
#mean()
arr1.mean()

13.4

In [18]:
#standard deviation
arr1.std()

2.4166091947189146

In [20]:
#median
arr1.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [21]:
#correlation coefficient
arr1.corrcoef()

AttributeError: 'numpy.ndarray' object has no attribute 'corrcoef'

In [19]:
import numpy as np

arr1 = np.array([[12, 14, 19, 25],[20, 13, 40, 18]])
print(arr1)
print(arr1.sum())
print(arr1.min())
print(arr1.max())
print(arr1.cumsum())
print(arr1.mean())
print(arr1.std())

[[12 14 19 25]
 [20 13 40 18]]
161
12
40
[ 12  26  45  70  90 103 143 161]
20.125
8.506431390424542


### Universal Functions (ufunc)
- __NumPy provides useful mathematical functions, which are called Universal Functions.__ These functions operate element-wise on an array, producing another array as output.  
__(1) sqrt()__ : provides the square root of every element in the array.  
__(2) cos()__ : gives cosine value for all elements in the array.  
__(3) sin()__ : gives sine value for all elements in the array.  
__(4) exp()__ : performs exponentiation on each element.  
__(5) floor()__ : returns the nearest smallest integer value of every element in the array.  
__(6) ceil()__ : returns the nearest largest value of every element in the array. 
__(7) dot()__ :  
__(8) inverse()__ :  returns inverse of the given array. It can be applied only on square matrix.  
__(9) inner()__ : 

In [1]:
import numpy as np

#sqrt()
np_sqrt = np.sqrt([2, 4, 9, 16])
np_sqrt    #square root values

array([1.41421356, 2.        , 3.        , 4.        ])

In [2]:
#cos()
np.cos(0)

1.0

In [3]:
from numpy import pi
np.cos(pi)

-1.0

In [4]:
#sin()
np.sin(0)

0.0

In [5]:
np.sin(pi/2)

1.0

In [6]:
#floor()
np.floor([1.5, 1.6, 2.7, 3.3, 1.1, -0.3, -1.4])

array([ 1.,  1.,  2.,  3.,  1., -1., -2.])

In [7]:
#ceil()
np.ceil([1.5, 1.6, 2.7, 3.3, 1.1, -0.3, -1.4])

array([ 2.,  2.,  3.,  4.,  2., -0., -1.])

In [8]:
#exp()
np.exp([0,1,5])

array([  1.        ,   2.71828183, 148.4131591 ])

In [17]:
#inverse()
array1 = np.array([[10,20],[15,25]])
print(array1)

inverse_array = np.linalg.inv(array1)
print(inverse_array)

[[10 20]
 [15 25]]
[[-0.5  0.4]
 [ 0.3 -0.2]]


## Shape Manipulation 
- The shape of a basic array can be changed according to the requirement by using numpy library functions. These array shape manipulation methods really come in handy during Data wrangling phase.
- Some common methods for manipulating shapes are:  
__(1) ravel():__ flatten your arrays. if you ever have 2D, 3D or n-D arrays, you can just use this function to flatten it all out to a 1-D array.  
__(2) reshape()__  
__(3) resize()__  
__(4) hsplit()__  
__(5) hstack():__ Stack arrays horizontally  
__(6) concatenate()__  
__(7) vstack():__ Stack arrays row-wise  
__(8) r_[ ]:__ Stack arrays row-wise  
__(8) column_stack():__ Stack arrays column-wise  
__(9) c_[ ]:__ Stack arrays column-wise

In [19]:
#ravel() flattens the dataset into a single row
new_cyclist_trials = np.array([[10, 15, 17, 26, 13, 19],[12, 11, 21, 24, 14, 23]])
new_cyclist_trials

array([[10, 15, 17, 26, 13, 19],
       [12, 11, 21, 24, 14, 23]])

In [20]:
new_cyclist_trials.ravel()

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])

- From Broadcasting concept we came to know that the dimensions of your arrays need to be compatible if you want them to be good candidates for arithmetic operations. But the question of what you should do when that is not the case. What you can do if the arrays don’t have the same dimensions, is resize your array. You will then return a new array that has the shape that you passed to the __np.resize()__ function. If you pass your original array together with the new dimensions, and if that new array is larger than the one that you originally had, the new array will be filled with copies of the original array that are repeated as many times as is needed. However, if you just apply np.resize() to the array and you pass the new shape to it, the new array will be filled with zeros.

In [21]:
#resize() resizes again to original dimensions
new_cyclist_trials.resize(2, 6)

In [22]:
new_cyclist_trials

array([[10, 15, 17, 26, 13, 19],
       [12, 11, 21, 24, 14, 23]])

In [23]:
arr1 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(arr1)

print(arr1.shape)

#resize arr1 to ((6, 4))
np.resize(arr1, (6,4))

print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [24]:
arr1.resize((6,4))
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 0  0  0  0]
 [ 0  0  0  0]
 [ 0  0  0  0]]


- Resizing means that you give a new shape to an array without changing its data. The key to reshaping is to make sure that the total size of the new array is unchanged. If you take the example of array arr1 that was used above, which has a size of 3 X 4 or 12, you have to make sure that the new array also has a size of 12.

In [25]:
#reshape() reshapes the dataset
new_cyclist_trials.reshape(3, 4)

array([[10, 15, 17, 26],
       [13, 19, 12, 11],
       [21, 24, 14, 23]])

In [26]:
#hsplit() splits the array
np.hsplit(new_cyclist_trials, 3)  #splits the array into 3 arrays. All 3 arrays will now contain 2 rows & 2 columns

[array([[10, 15],
        [12, 11]]),
 array([[17, 26],
        [21, 24]]),
 array([[13, 19],
        [14, 23]])]

In [27]:
np.hsplit(new_cyclist_trials, 2) #splits the array into 2 arrays.

[array([[10, 15, 17],
        [12, 11, 21]]),
 array([[26, 13, 19],
        [24, 14, 23]])]

In [28]:
#hstack() stacks the arrays together
new_cyclist_1 = np.array([10, 15, 17, 26, 13, 19])
new_cyclist_2 = np.array([12, 11, 21, 24, 14, 23])

np.hstack((new_cyclist_1, new_cyclist_2))

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])

- __Transpose :__ NumPy can carry out linear algebraic functions. The transpose() function can help you to interchange rows as columns and vice-versa.

In [13]:
test_scores = np.array([[83, 71, 57, 63],[54, 68, 81, 45]])
test_scores

array([[83, 71, 57, 63],
       [54, 68, 81, 45]])

In [14]:
test_scores.transpose()

array([[83, 54],
       [71, 68],
       [57, 81],
       [63, 45]])

In [15]:
np.transpose(test_scores)

array([[83, 54],
       [71, 68],
       [57, 81],
       [63, 45]])

In [18]:
test_scores.T     #this also returns the transpose of an array

array([[83, 54],
       [71, 68],
       [57, 81],
       [63, 45]])

In [16]:
#transpose() of a 1D array returns the same unchanged array
a = np.array([10, 12, 13])
a.transpose()

array([10, 12, 13])

- There is no effect when you transpose a 1-D array.

In [12]:
arr1 = np.array([1, 2, 3, 4, 5])

np.transpose(arr1)

array([1, 2, 3, 4, 5])

- __Trace() :__ helps in getting the sum of the diagonal elements of the array. It is applied from left to right and not vice-versa.

In [114]:
array_2 = np.array([[10, 20],[22, 31]])
array_2

array([[10, 20],
       [22, 31]])

In [117]:
trace_array = np.trace(array_2)    #sum of diagonal elements 10 and 31
trace_array

41

### Append Arrays:
- When you append arrays to your original array, they are “glued” to the end of that original array. If you want to make sure that what you append does not come at the end of the array, you might consider inserting it.

In [23]:
import numpy as np

my_array = np.array([3, 5, 7, 9])
print(my_array)

new_array = np.append(my_array, [2, 4, 6, 8])
print(new_array)

[3 5 7 9]
[3 5 7 9 2 4 6 8]


In [26]:
#append an extra column to an 2D array
arr2 = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
print(arr2)

arr2_new = np.append(arr2, [[7],[8]], axis = 1)
print(arr2_new)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4 7]
 [5 6 7 8 8]]


- When you append an extra column to arr2_new, the axis is specified. Remember that axis 1 indicates the columns, while axis 0 indicates the rows in 2-D arrays.

In [29]:
arr2_new2 = np.append(arr2, [[7],[8]])
print(arr2_new2)

[1 2 3 4 5 6 7 8 7 8]


### Insert And Delete Array Elements:
- The functions that will allow you to do these operations are __np.insert()__ and __np.delete()__.

In [33]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])

np.insert(arr1, 1, 7)    #here 1 is the index number

array([1, 7, 2, 3, 4])

In [32]:
print(arr1)   #insert() will not update the initial array.

[1 2 3 4]


In [35]:
arr1 = np.array([1, 2, 3, 4])

np.delete(arr1, [1])

array([1, 3, 4])

In [37]:
print(arr1)   #delete() will not update the initial array.

[1 2 3 4]


### Join And Split Arrays:

In [38]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

In [39]:
#Concatentate arr1 and arr2
print(np.concatenate((arr1, arr2)))

[1 2 3 4 5 6 7 8]


- The number of dimensions needs to be the same if you want to concatenate two arrays with __np.concatenate()__.

In [40]:
#Stack arrays row-wise
print(np.vstack((arr1, arr2)))

[[1 2 3 4]
 [5 6 7 8]]


- You just have to make sure that, as you’re stacking the arrays row-wise, that the number of columns in both arrays is the same. the arrays must have the same shape along all but the first axis. The same holds also for when you want to use __np.r_[ ]__.

In [41]:
#Stack arrays row-wise
print(np.r_[arr1, arr2])

[1 2 3 4 5 6 7 8]


In [42]:
#Stack arrays horizontally
print(np.hstack((arr1, arr2)))

[1 2 3 4 5 6 7 8]


- For __np.hstack()__, you have to make sure that the number of dimensions is the same and that the number of rows in both arrays is the same. Anything is possible as long as you make sure that the number of rows matches. This function is still supported by NumPy, but you should prefer np.concatenate() or np.stack().

In [43]:
#Stack arrays column-wise
print(np.column_stack((arr1, arr2)))

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


- With __np.column_stack()__, you have to make sure that the arrays that you input have the same first dimension.

In [44]:
#Stack arrays column-wise
print(np.c_[arr1, arr2])

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


- __np.c_[ ]__ is another way to concatenate. Here also, the first dimension of both arrays needs to match.

- When you have joined arrays, you might also want to split them at some point. Just like you can stack them horizontally, you can also do the same but then vertically. You use __np.hsplit()__ and __np.vsplit()__, respectively.

In [47]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])

#Split `arr1` horizontally at the 2nd index
print(np.hsplit(arr1, 2))

arr2 = np.array([5, 6, 7, 8, 9])
#Split `arr2` horizontally at the 2nd index
print(np.hsplit(arr2, 2))

[array([1, 2]), array([3, 4])]


ValueError: array split does not result in an equal division

In [48]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])

#Split `arr1` vertically at the 2nd index
print(np.vsplit(arr1, 2))

ValueError: vsplit only works on arrays of 2 or more dimensions

In [53]:
arr1 = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
print(arr1)

#Split `arr1` vertically at the 2nd index
print(np.vsplit(arr1, 2))

[[1 2 3 4]
 [5 6 7 8]]
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


### Practice Project: GDP of countries Analysis
DESCRIPTION

__Problem Statement:__ Evaluate the dataset containing the GDPs of different countries to:

- Find and print the name of the country with the highest GDP
- Find and print the name of the country with the lowest GDP
- Print out text and input values iteratively
- Print out the entire list of the countries with their GDPs
- Print the highest GDP value, lowest GDP value, mean GDP value, standardized GDP value, and the sum of all the GDPs

In [119]:
import numpy as np
gdp = open("D:\PGP_DataScience_Purdue_Simplilearn\Python Practice\Lesson 5\GDP dataset\Countries with GDP.txt", "r")
gdp.read()

"List of countries:\n\n'Algeria','Angola','Argentina','Australia','Austria','Bahamas','Bangladesh','Belarus','Belgium','Bhutan','Brazil','Bulgaria','Cambodia','Cameroon','Chile','China','Colombia','Cyprus','Denmark','El Salvador','Estonia','Ethiopia','Fiji','Finland','France','Georgia','Ghana','Grenada','Guinea','Haiti','Honduras','Hungary','India','Indonesia','Ireland','Italy','Japan','Kenya', 'South Korea','Liberia','Malaysia','Mexico', 'Morocco','Nepal','New Zealand','Norway','Pakistan', 'Peru','Qatar','Russia','Singapore','South Africa','Spain','Sweden','Switzerland','Thailand', 'United Arab Emirates','United Kingdom','United States','Uruguay','Venezuela','Vietnam','Zimbabwe'\n\n\nGDP values for each country:\n\n2255.225482,629.9553062,11601.63022,25306.82494,27266.40335,19466.99052,588.3691778,2890.345675,24733.62696,1445.760002,4803.398244,2618.876037,590.4521124,665.7982328,7122.938458,2639.54156,3362.4656,15378.16704,30860.12808,2579.115607,6525.541272,229.6769525,2242.689259,2

In [122]:
countries = np.array(['Algeria','Angola','Argentina','Australia','Austria','Bahamas','Bangladesh','Belarus','Belgium','Bhutan','Brazil','Bulgaria','Cambodia','Cameroon','Chile','China','Colombia','Cyprus','Denmark','El Salvador','Estonia','Ethiopia','Fiji','Finland','France','Georgia','Ghana','Grenada','Guinea','Haiti','Honduras','Hungary','India','Indonesia','Ireland','Italy','Japan','Kenya', 'South Korea','Liberia','Malaysia','Mexico', 'Morocco','Nepal','New Zealand','Norway','Pakistan', 'Peru','Qatar','Russia','Singapore','South Africa','Spain','Sweden','Switzerland','Thailand', 'United Arab Emirates','United Kingdom','United States','Uruguay','Venezuela','Vietnam','Zimbabwe'])

gdp_per_capita = np.array([2255.225482,629.9553062,11601.63022,25306.82494,27266.40335,19466.99052,588.3691778,2890.345675,24733.62696,1445.760002,4803.398244,2618.876037,590.4521124,665.7982328,7122.938458,2639.54156,3362.4656,15378.16704,30860.12808,2579.115607,6525.541272,229.6769525,2242.689259,27570.4852,23016.84778,1334.646773,402.6953275,6047.200797,394.1156638,385.5793827,1414.072488,5745.981529,837.7464011,1206.991065,27715.52837,18937.24998,39578.07441,478.2194906,16684.21278,279.2204061,5345.213415,6288.25324,1908.304416,274.8728621,14646.42094,40034.85063,672.1547506,3359.517402,36152.66676,3054.727742,33529.83052,3825.093781,15428.32098,33630.24604,39170.41371,2699.123242,21058.43643,28272.40661,37691.02733,9581.05659,5671.912202,757.4009286,347.7456605])

In [123]:
max_gdp_per_capita = gdp_per_capita.argmax()  #argmax() function returns indices of the max element of the array
max_gdp_per_capita

45

In [126]:
country_with_max_gdp_per_capita = countries[max_gdp_per_capita]
country_with_max_gdp_per_capita     #country with highest GDP

'Norway'

In [127]:
min_gdp_per_capita = gdp_per_capita.argmin()
min_gdp_per_capita

21

In [128]:
country_with_min_gdp_per_capita = countries[min_gdp_per_capita]
country_with_min_gdp_per_capita     #country with lowest GDP

'Ethiopia'

In [140]:
#printing out text and input values iteratively
for country in countries:
    print("country name: {}".format(country))

country name: Algeria
country name: Angola
country name: Argentina
country name: Australia
country name: Austria
country name: Bahamas
country name: Bangladesh
country name: Belarus
country name: Belgium
country name: Bhutan
country name: Brazil
country name: Bulgaria
country name: Cambodia
country name: Cameroon
country name: Chile
country name: China
country name: Colombia
country name: Cyprus
country name: Denmark
country name: El Salvador
country name: Estonia
country name: Ethiopia
country name: Fiji
country name: Finland
country name: France
country name: Georgia
country name: Ghana
country name: Grenada
country name: Guinea
country name: Haiti
country name: Honduras
country name: Hungary
country name: India
country name: Indonesia
country name: Ireland
country name: Italy
country name: Japan
country name: Kenya
country name: South Korea
country name: Liberia
country name: Malaysia
country name: Mexico
country name: Morocco
country name: Nepal
country name: New Zealand
country na

In [138]:
#entire list of countries & their GDPs
for i in range(len(countries)):
    country = countries[i]
    country_gdp_per_capita = gdp_per_capita[i]
    print("per capita gdp of {} is {}".format(country, country_gdp_per_capita))

per capita gdp of Algeria is 2255.225482
per capita gdp of Angola is 629.9553062
per capita gdp of Argentina is 11601.63022
per capita gdp of Australia is 25306.82494
per capita gdp of Austria is 27266.40335
per capita gdp of Bahamas is 19466.99052
per capita gdp of Bangladesh is 588.3691778
per capita gdp of Belarus is 2890.345675
per capita gdp of Belgium is 24733.62696
per capita gdp of Bhutan is 1445.760002
per capita gdp of Brazil is 4803.398244
per capita gdp of Bulgaria is 2618.876037
per capita gdp of Cambodia is 590.4521124
per capita gdp of Cameroon is 665.7982328
per capita gdp of Chile is 7122.938458
per capita gdp of China is 2639.54156
per capita gdp of Colombia is 3362.4656
per capita gdp of Cyprus is 15378.16704
per capita gdp of Denmark is 30860.12808
per capita gdp of El Salvador is 2579.115607
per capita gdp of Estonia is 6525.541272
per capita gdp of Ethiopia is 229.6769525
per capita gdp of Fiji is 2242.689259
per capita gdp of Finland is 27570.4852
per capita gdp 

In [132]:
#Highest GDP value
gdp_per_capita.max()

40034.85063

In [133]:
#lowest GDP value
gdp_per_capita.min()

229.6769525

In [134]:
#Mean GDP
gdp_per_capita.mean()

11289.409271639683

In [135]:
#standardized GDP value
gdp_per_capita.std()

12743.828910617945

In [137]:
#sum of all GDPs
gdp_per_capita.sum()

711232.7841133

### Practice Project : London Olympics Dataset Analysis
DESCRIPTION

Problem: 

Evaluate the dataset of the Summer Olympics, London 2012 to:

- Find and print the name of the country that won maximum gold medals,
- Find and print the countries who won more than 20 gold medals,
- Print the medal tally,
- Print each country name with the corresponding number of gold medals, and
- Print each country's name with the total number of medals won.

In [30]:
import numpy as np

#Dataset from summer Olympic London, year 2012
np_olympic_country = np.array(['GBR','China','RUS','US','KOR','JPN','GER'])
np_olympic_country_Gold = np.array([29, 38, 24, 46, 13, 7, 11])
np_olympic_country_Silver = np.array([17, 28, 25, 28, 8, 14, 11])
np_olympic_country_Bronze = np.array([19, 22, 32, 29, 7, 17, 14])

In [31]:
#finding country index with maximum Gold
np_olympic_max_Gold = np_olympic_country_Gold.argmax()
np_olympic_max_Gold

3

In [32]:
#country that won maximum gold medals
np_olympic_country_with_max_Gold = np_olympic_country[np_olympic_max_Gold]
np_olympic_country_with_max_Gold

'US'

In [33]:
#country won more than 20 Gold medals, using boolean indexing technique
np_olympic_country_with_Gold_more_than20 = np_olympic_country[np_olympic_country_Gold > 20]
np_olympic_country_with_Gold_more_than20

array(['GBR', 'China', 'RUS', 'US'], dtype='<U5')

In [34]:
#creating medal tally
#each country name with number of gold medals & total number of medals
for i in range(len(np_olympic_country)):
    gold_medal = np_olympic_country_Gold[i]
    country = np_olympic_country[i]
    total_medal = np_olympic_country_Gold[i] + np_olympic_country_Silver[i] + np_olympic_country_Bronze[i]
    print("{} ---> Gold medal {}, Total medal {}".format(country, gold_medal, total_medal))

GBR ---> Gold medal 29, Total medal 65
China ---> Gold medal 38, Total medal 88
RUS ---> Gold medal 24, Total medal 81
US ---> Gold medal 46, Total medal 103
KOR ---> Gold medal 13, Total medal 28
JPN ---> Gold medal 7, Total medal 38
GER ---> Gold medal 11, Total medal 36


In [37]:
#Printing each country name with the corresponding number of gold medals
for i in range(len(np_olympic_country)):
    gold_medal = np_olympic_country_Gold[i]
    country = np_olympic_country[i]
    print(country + " :", gold_medal)

GBR : 29
China : 38
RUS : 24
US : 46
KOR : 13
JPN : 7
GER : 11


In [38]:
#Printing each country name with total number of medals won
for i in range(len(np_olympic_country)):
    country = np_olympic_country[i]
    total_medal = np_olympic_country_Gold[i] + np_olympic_country_Silver[i] + np_olympic_country_Bronze[i]
    print(country + " :", total_medal)

GBR : 65
China : 88
RUS : 81
US : 103
KOR : 28
JPN : 38
GER : 36


In [1]:
a = 10, 20, 30, 40
print(a)

(10, 20, 30, 40)


In [2]:
print("Hello {1!r} and {0!s}".format('Himansu', 'Tarun'))

Hello 'Tarun' and Himansu


In [4]:
import pandas as pd

In [ ]:
pd.read_csv()